---
title: "Fangorn"
output: html_notebook
---
```{r}
set.seed(25000)
library(tidyverse)
library(ggplot2)
library(cowplot)
library(randomForest)
library(parallel)
library(skimr)
library(broom)
library(janitor)
library(dplyr)
library(readr)
library(genefilter)
#library(parLapply)
```

```{r import}
# Read in the cleaned expression data
expression <- as.data.frame((read.table("../data/clean_expression.txt", row.names=1 )))
rownames(expression)[1] <- '184A1'# Rename the only integer name

# Read in the subtype data
subtypes <- read_tsv("../data/clean_subtypes.txt")

# Read in the truth set
truth_set <-  as.data.frame((read.table("../data/clean_training_answers.txt", row.names=1 )))


# Create merged feature set
featureSet<-cbind(subtypes[,2],t(expression))
```
#variance 
```{r}
expVar <- (rowVars(expression))
hist(expVar)
expVar <- as.data.frame(expVar)
names(expVar) <- c('variance')

paste('max variance:', max(expVar[,1]))
paste('min variance:', min(expVar[,1]))

#top 20 of genes
expVar %>% count((variance > '0.5'))
top20 <- expVar$variance > 0.5 
root20 <- expression[top20,]
dim(root20)




#top 10% of genes
expVar %>% count((variance > '1'))
top10 <- expVar$variance > 1 
root10 <- expression[top10,]
root10<-data.frame(t(root10))
dim(root10)




#top 5% of genes
expVar %>% count((variance > '1.5'))
top5 <- expVar$variance > 1.5 
root5 <- expression[top5,]
root5<-data.frame(t(root10))
dim(root5)



```

#forest 1
```{r drug 1 roots}
#straping the first column of the truth set to the tree
tree120<-cbind(drug=truth_set[,1],root20)
tree120<-clean_names(tree120)
tree120$drug<-factor(tree120$drug)


tree110<-cbind(drug=truth_set[,1],root10)
tree110<-clean_names(tree110)
tree110$drug<-factor(tree110$drug)


tree105<-cbind(drug=truth_set[,1],root5)
tree105<-clean_names(tree105)
tree105$drug<-factor(tree105$drug)

```


```{r primary run forrest drug 1}
set.seed(25000)
#BAROOM dont be hasty now

oldForest <- randomForest( drug∼.,data=tree105  ,mtry=3,ntree=2000)
oldForest

mirkwood <- randomForest( drug∼.,data=tree110  ,mtry=3,ntree=2000)
mirkwood

fangorn <- randomForest( drug∼.,data=tree120  ,mtry=3,ntree=2000)
fangorn

```

```{r optimise trees optimise tree count drug 1}
set.seed(25000)
#tree optimization for 5% tree
oob.error.oldForest <- data.frame(
  Trees=rep(1:nrow(oldForest$err.rate), times=3),
  Type=rep(c("OOB", "1", "0"), each=nrow(oldForest$err.rate)),
  Error=c(oldForest$err.rate[,"OOB"],
    oldForest$err.rate[,"1"],
    oldForest$err.rate[,"0"]))

#tree optimization for 10% tree
oob.error.mirkwood <- data.frame(
  Trees=rep(1:nrow(mirkwood$err.rate), times=3),
  Type=rep(c("OOB", "1", "0"), each=nrow(mirkwood$err.rate)),
  Error=c(mirkwood$err.rate[,"OOB"],
    mirkwood$err.rate[,"1"],
    mirkwood$err.rate[,"0"]))

#tree optimization for 20% tree
oob.error.fangorn<- data.frame(
  Trees=rep(1:nrow(fangorn$err.rate), times=3),
  Type=rep(c("OOB", "1", "0"), each=nrow(fangorn$err.rate)),
  Error=c(fangorn$err.rate[,"OOB"],
    fangorn$err.rate[,"1"],
    fangorn$err.rate[,"0"]))

#tree optimization plot for 5% tree
ggplot(data=oob.error.oldForest, aes(x=Trees, y=Error)) +
  geom_line(aes(color=Type))+ggtitle("forest of 5% variance")

#tree optimization plot for 10% tree
ggplot(data=oob.error.mirkwood, aes(x=Trees, y=Error)) +
  geom_line(aes(color=Type))+ggtitle("forest of 10% variance")

#tree optimization for 20% tree
ggplot(data=oob.error.fangorn, aes(x=Trees, y=Error)) +
  geom_line(aes(color=Type))+ggtitle("forest of 20% variance")
```

```{r optimising splits drug 1}
set.seed(25000)
#split optimization
oob.values <- vector(length=20)
for(i in 1:20) {
  temp.model <- randomForest(drug ~ ., data=tree105, mtry=i, ntree=2000)
  oob.values[i] <- temp.model$err.rate[nrow(temp.model$err.rate),1]
}
oob.values

oob.values <- vector(length=20)
for(i in 1:20) {
  temp.model <- randomForest(drug ~ ., data=tree110, mtry=i, ntree=2000)
  oob.values[i] <- temp.model$err.rate[nrow(temp.model$err.rate),1]
}
oob.values

oob.values <- vector(length=20)
for(i in 1:20) {
  temp.model <- randomForest(drug ~ ., data=tree120, mtry=i, ntree=2000)
  oob.values[i] <- temp.model$err.rate[nrow(temp.model$err.rate),1]
}
oob.values
```

```{r Optimised forrests for drug 1}
set.seed(25000)
#BAROOM dont be hasty now
#roots<-as.matrix(tree1)

oldForest <- randomForest( drug∼.,data=tree105  ,mtry=13,ntree=2000)
oldForest

mirkwood <- randomForest( drug∼.,data=tree110  ,mtry=18,ntree=2000)
mirkwood

fangorn <- randomForest( drug∼.,data=tree120  ,mtry=5,ntree=2000)
fangorn
```

#forest 2
```{r drug 2 roots}
tree220<-cbind(drug=truth_set[,2],root20)
tree220<-clean_names(tree220)
tree220$drug<-factor(tree220$drug)


tree210<-cbind(drug=truth_set[,2],root10)
tree210<-clean_names(tree210)
tree210$drug<-factor(tree210$drug)


tree205<-cbind(drug=truth_set[,2],root5)
tree205<-clean_names(tree205)
tree205$drug<-factor(tree205$drug)

```

```{r primary run forrest drug 2}
set.seed(25000)
#BAROOM dont be hasty now

oldForest2 <- randomForest( drug∼.,data=tree205  ,mtry=3,ntree=500)
oldForest2

mirkwood2 <- randomForest( drug∼.,data=tree210  ,mtry=3,ntree=500)
mirkwood2

fangorn2 <- randomForest( drug∼.,data=tree220  ,mtry=3,ntree=500)
fangorn2

```

```{r tree optimization drug2}
#tree optimization for 5% tree
oob.error.oldForest2 <- data.frame(
  Trees=rep(1:nrow(oldForest2$err.rate), times=3),
  Type=rep(c("OOB", "1", "0"), each=nrow(oldForest2$err.rate)),
  Error=c(oldForest2$err.rate[,"OOB"],
    oldForest2$err.rate[,"1"],
    oldForest2$err.rate[,"0"]))

#tree optimization for 10% tree
oob.error.mirkwood2 <- data.frame(
  Trees=rep(1:nrow(mirkwood2$err.rate), times=3),
  Type=rep(c("OOB", "1", "0"), each=nrow(mirkwood2$err.rate)),
  Error=c(mirkwood2$err.rate[,"OOB"],
    mirkwood2$err.rate[,"1"],
    mirkwood2$err.rate[,"0"]))

#tree optimization for 20% tree
oob.error.fangorn2<- data.frame(
  Trees=rep(1:nrow(fangorn2$err.rate), times=3),
  Type=rep(c("OOB", "1", "0"), each=nrow(fangorn2$err.rate)),
  Error=c(fangorn2$err.rate[,"OOB"],
    fangorn2$err.rate[,"1"],
    fangorn2$err.rate[,"0"]))

#tree optimization plot for 5% tree
ggplot(data=oob.error.oldForest2, aes(x=Trees, y=Error)) +
  geom_line(aes(color=Type))+ggtitle("forest of 5% variance")

#tree optimization plot for 10% tree
ggplot(data=oob.error.mirkwood2, aes(x=Trees, y=Error)) +
  geom_line(aes(color=Type))+ggtitle("forest of 10% variance")

#tree optimization for 20% tree
ggplot(data=oob.error.fangorn2, aes(x=Trees, y=Error)) +
  geom_line(aes(color=Type))+ggtitle("forest of 20% variance")
```
```{r split optimization for drug 2}
set.seed(25000)
#split optimization
oob.values <- vector(length=20)
for(i in 1:20) {
  temp.model <- randomForest(drug ~ ., data=tree205, mtry=i, ntree=500)
  oob.values[i] <- temp.model$err.rate[nrow(temp.model$err.rate),1]
}
oob.values

oob.values <- vector(length=20)
for(i in 1:20) {
  temp.model <- randomForest(drug ~ ., data=tree210, mtry=i, ntree=500)
  oob.values[i] <- temp.model$err.rate[nrow(temp.model$err.rate),1]
}
oob.values

oob.values <- vector(length=20)
for(i in 1:20) {
  temp.model <- randomForest(drug ~ ., data=tree220, mtry=i, ntree=500)
  oob.values[i] <- temp.model$err.rate[nrow(temp.model$err.rate),1]
}
oob.values
```

```{r final paramaters drug2}
set.seed(25000)
#BAROOM dont be hasty now

oldForest2 <- randomForest( drug∼.,data=tree205  ,mtry=2,ntree=500)
oldForest2

mirkwood2 <- randomForest( drug∼.,data=tree210  ,mtry=2,ntree=500)
mirkwood2

fangorn2 <- randomForest( drug∼.,data=tree220  ,mtry=2,ntree=500)
fangorn2
```

