---
title: "Analysis Plan"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# EDA

### Understanding the data

- # of features: cell subtypes? genes in expression data?
- How many observations in the training set?
- What is the variance? Grouped by cell line? sub type?

<br>

### Looking at the consequences of the study design

- batch effect - human, machine, dates? READ THE DAMN PAPER.

<br>

### Looking at the biology

- What cell lines are being used? Where are the cell lines derived from?
- What is the difference in the different cell line sub-types?

<br> <br> <br>




# Methods

### LDA/QDA

- lower complexity model compared to neural net
- low bias, high variance
- Naive approach with LDA and compare that to QDA to test model performance by increasing the model complexity 

- Potential method of normalization: 

<br>

### Random forest / ensembl method

- bagging methodology: random sampling to avoid overfitting
- higher complexity model
-high bias, low variance

<br>

### Neural net

- high complexity model 
- high bias, low variance

<br>

### SVM

- ??? maybe? 